<div class="space-y-6" @if ($pollFrequently) wire:poll.visible.10s @endif>
    @php
        $formatTime = static fn ($time) => $time?->copy()->timezone(config('app.timezone'))->format('d.m.Y. H:i:s') ?? '—';
        $statusTone = static fn ($status) => match ($status) {
            'completed', 'imported' => 'bg-emerald-100 text-emerald-800',
            'failed' => 'bg-rose-100 text-rose-800',
            'queued', 'running' => 'bg-cyan-100 text-cyan-800',
            'skipped' => 'bg-amber-100 text-amber-800',
            default => 'bg-slate-100 text-slate-700',
        };
    @endphp

    <section class="admin-panel admin-search-panel p-5 sm:p-6">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">{{ __('Integracije') }}</p><h1 class="mt-2 text-xl font-semibold tracking-tight text-slate-900">{{ __('Uvoz slika') }}</h1><p class="mt-2 max-w-3xl text-sm text-slate-600">{{ __('Dohvatite ERP glavne slike koje nedostaju ili dodajte Braytron slike galerije. Obrada radi u pozadini, do 100 artikala po pokretanju.') }}</p><p class="mt-2 text-xs text-slate-500">{{ __('Postojeće ručno unesene slike se čuvaju. Ponovljene slike se preskaču.') }}</p></div><button type="button" wire:click="$refresh" wire:loading.attr="disabled" class="min-h-10 rounded-xl border border-slate-300 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 disabled:opacity-40">{{ __('Osvježi pregled') }}</button></div>
    </section>

    <section class="admin-panel admin-panel-soft p-5">
        <div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="admin-section-title">{{ __('Izvor i kandidati') }}</h2><label for="media-import-kind" class="mb-1 mt-3 block text-xs font-semibold text-slate-500">{{ __('Izvor slika') }}</label><select id="media-import-kind" wire:model.live="kind" class="admin-select rounded-xl border border-slate-300 px-3 py-2 text-sm">@foreach ($kindLabels as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $configured ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800' }}">{{ $configured ? __('Izvor je podešen') : __('Izvor nije podešen') }}</span></div>
        @if (! $configured)<p class="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{{ __('Prvo treba podesiti odgovarajuću dobavljačku integraciju.') }}</p>@endif
        <p class="mt-4 text-xs text-slate-500">{{ __('Pronađeno kandidata') }}: <strong>{{ number_format($candidateCount, 0, ',', '.') }}</strong> · {{ __('Za odabir je prikazano prvih 100. Možete pokrenuti odabrane artikle ili cijeli prvi paket.') }}</p>
        <div class="mt-4 overflow-x-auto"><table class="admin-items-table min-w-[34rem] text-sm"><thead><tr class="text-left text-xs text-slate-500"><th class="px-3 py-2 font-semibold">{{ __('Odabir') }}</th><th class="px-3 py-2 font-semibold">{{ __('Šifra') }}</th><th class="px-3 py-2 font-semibold">{{ __('Artikl') }}</th><th class="px-3 py-2 font-semibold">{{ __('ID artikla') }}</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($candidates as $candidate)<tr wire:key="media-candidate-{{ $kind }}-{{ $candidate['id'] }}"><td class="px-3 py-3"><input type="checkbox" wire:model.live="selectedProductIds" value="{{ $candidate['id'] }}" aria-label="{{ __('Odaberi :name', ['name' => $candidate['name']]) }}" class="h-4 w-4 rounded border-slate-300 text-cyan-700 focus:ring-cyan-600"></td><td class="px-3 py-3 font-mono text-xs">{{ $candidate['identifier'] }}</td><td class="px-3 py-3 text-sm text-slate-800">{{ $candidate['name'] }}</td><td class="px-3 py-3 text-xs">{{ $candidate['id'] }}</td></tr>@empty<tr><td colspan="4" class="px-3 py-8 text-center text-sm text-slate-500">{{ __('Nema dostupnih kandidata za odabrani izvor.') }}</td></tr>@endforelse</tbody></table></div>
        <div class="mt-4">{{ $candidates->links() }}</div>
        <div class="mt-5 flex flex-wrap gap-3 border-t border-slate-200 pt-4"><button type="button" wire:click="startSelected" wire:loading.attr="disabled" @disabled(! $configured || count($selectedProductIds) === 0) class="min-h-11 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-40">{{ __('Pokreni odabrane') }} ({{ count($selectedProductIds) }})</button><button type="button" wire:click="startBatch" wire:loading.attr="disabled" @disabled(! $configured || $candidateCount === 0) class="min-h-11 rounded-xl border border-cyan-300 bg-cyan-50 px-4 py-2 text-sm font-semibold text-cyan-800 hover:bg-cyan-100 disabled:cursor-not-allowed disabled:opacity-40">{{ __('Pokreni prvi paket') }} ({{ min(100, $candidateCount) }})</button><button type="button" wire:click="clearSelection" class="min-h-11 rounded-xl border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100">{{ __('Očisti odabir') }}</button></div>
        <p wire:loading wire:target="startSelected,startBatch" role="status" class="mt-3 text-xs font-semibold text-cyan-800">{{ __('Pripremam obradu u pozadini…') }}</p>
        @if ($errors->any())<ul class="mt-4 space-y-1 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>@endif
    </section>

    @if ($selectedRun)
        <section wire:key="media-report-{{ $selectedRun->id }}" class="admin-panel admin-panel-soft p-5" aria-labelledby="media-report-title">
            <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 id="media-report-title" class="admin-section-title">{{ __('Izvještaj slika') }} #{{ $selectedRun->id }}</h2><p class="mt-2 text-xs text-slate-500">{{ $kindLabels[$selectedRun->kind] }} · {{ $statusLabels[$selectedRun->status] ?? $selectedRun->status }} · {{ __('Početak') }}: {{ $formatTime($selectedRun->started_at) }} · {{ __('Završetak') }}: {{ $formatTime($selectedRun->completed_at) }}</p></div><button type="button" wire:click="closeReport" class="min-h-9 rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100">{{ __('Zatvori izvještaj') }}</button></div>
            @if ($selectedRun->error_message)<p class="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert">{{ $selectedRun->error_message }}</p>@endif
            @if ($canRetry)
                <div class="mt-4 flex flex-wrap items-center gap-3"><button type="button" wire:click="retryReport" wire:loading.attr="disabled" class="min-h-10 rounded-xl border border-cyan-300 bg-cyan-50 px-4 py-2 text-xs font-semibold text-cyan-800 hover:bg-cyan-100 disabled:opacity-40">{{ __('Ponovi preskočene/neuspjele') }}</button><p class="text-xs text-slate-500">{{ __('Ponovno se obrađuju samo preskočene i neuspjele stavke ovog izvještaja, do 100 artikala.') }}</p></div>
                <p wire:loading wire:target="retryReport" role="status" class="mt-2 text-xs font-semibold text-cyan-800">{{ __('Pripremam ponovnu obradu…') }}</p>
            @endif
            <dl class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6">@foreach (['fetched_count' => __('U paketu'), 'updated_count' => __('Artikala s novim slikama'), 'unchanged_count' => __('Bez promjene'), 'skipped_count' => __('Preskočeno')] as $field => $label)<div class="rounded-xl bg-slate-50 px-3 py-3"><dt class="text-xs text-slate-500">{{ $label }}</dt><dd class="mt-1 text-lg font-semibold text-slate-900">{{ number_format((int) $selectedRun->{$field}, 0, ',', '.') }}</dd></div>@endforeach<div class="rounded-xl bg-slate-50 px-3 py-3"><dt class="text-xs text-slate-500">{{ __('Dodanih slika') }}</dt><dd class="mt-1 text-lg font-semibold text-slate-900">{{ (int) data_get($selectedRun->summary, 'images_added', 0) }}</dd></div><div class="rounded-xl bg-slate-50 px-3 py-3"><dt class="text-xs text-slate-500">{{ __('Neuspjelo artikala') }}</dt><dd class="mt-1 text-lg font-semibold text-slate-900">{{ (int) data_get($selectedRun->summary, 'failed_count', 0) }}</dd></div></dl>
            @if (data_get($selectedRun->summary, 'duplicate_count', 0) > 0)<p class="mt-3 text-xs text-slate-500">{{ __('Preskočenih ponovljenih slika') }}: {{ (int) data_get($selectedRun->summary, 'duplicate_count') }}</p>@endif
            <div class="mt-4 overflow-x-auto"><table class="admin-items-table min-w-[40rem] text-sm"><thead><tr class="text-left text-xs text-slate-500"><th class="px-3 py-2 font-semibold">{{ __('Šifra') }}</th><th class="px-3 py-2 font-semibold">{{ __('Artikl') }}</th><th class="px-3 py-2 font-semibold">{{ __('Rezultat') }}</th><th class="px-3 py-2 font-semibold">{{ __('Napomena') }}</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($items as $item)<tr wire:key="media-item-{{ $item->id }}"><td class="px-3 py-3 font-mono text-xs">{{ $item->identifier }}</td><td class="px-3 py-3 text-sm">{{ $item->name }}</td><td class="px-3 py-3 text-xs">{{ $itemStatusLabels[$item->status] ?? $item->status }}</td><td class="max-w-sm px-3 py-3 text-xs text-slate-500">{{ $item->message ?: '—' }}</td></tr>@empty<tr><td colspan="4" class="px-3 py-8 text-center text-sm text-slate-500">{{ __('Nema stavki za prikaz.') }}</td></tr>@endforelse</tbody></table></div>
            <div class="mt-4">{{ $items->links() }}</div>
        </section>
    @endif

    <section class="admin-panel admin-panel-soft p-5">
        <div class="flex flex-wrap items-end justify-between gap-3"><h2 class="admin-section-title">{{ __('Povijest obrade slika') }}</h2><div class="flex flex-wrap gap-3"><div><label for="media-kind-filter" class="mb-1 block text-xs font-semibold text-slate-500">{{ __('Izvor') }}</label><select id="media-kind-filter" wire:model.live="kindFilter" class="admin-select rounded-xl border border-slate-300 px-3 py-2 text-xs"><option value="all">{{ __('Svi izvori') }}</option>@foreach ($kindLabels as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div><label for="media-status-filter" class="mb-1 block text-xs font-semibold text-slate-500">{{ __('Status') }}</label><select id="media-status-filter" wire:model.live="statusFilter" class="admin-select rounded-xl border border-slate-300 px-3 py-2 text-xs"><option value="all">{{ __('Svi statusi') }}</option>@foreach ($statusLabels as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div></div></div>
        <div class="mt-4 overflow-x-auto"><table class="admin-items-table min-w-[48rem] text-sm"><thead><tr class="text-left text-xs text-slate-500"><th class="px-3 py-2 font-semibold">{{ __('Izvor / početak') }}</th><th class="px-3 py-2 font-semibold">{{ __('Status') }}</th><th class="px-3 py-2 text-right font-semibold">{{ __('U paketu') }}</th><th class="px-3 py-2 text-right font-semibold">{{ __('Dodanih slika') }}</th><th class="px-3 py-2 text-right font-semibold">{{ __('Izvještaj') }}</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($runs as $run)<tr wire:key="media-run-{{ $run->id }}"><td class="px-3 py-3"><p class="font-semibold text-slate-800">{{ $kindLabels[$run->kind] }}</p><p class="mt-1 text-xs text-slate-500">#{{ $run->id }} · {{ $formatTime($run->started_at) }}</p></td><td class="px-3 py-3"><span class="inline-flex rounded-full px-2 py-1 text-xs font-semibold {{ $statusTone($run->status) }}">{{ $statusLabels[$run->status] ?? $run->status }}</span></td><td class="px-3 py-3 text-right tabular-nums">{{ $run->fetched_count }}</td><td class="px-3 py-3 text-right tabular-nums">{{ (int) data_get($run->summary, 'images_added', 0) }}</td><td class="px-3 py-3 text-right"><button type="button" wire:click="selectRun({{ $run->id }})" class="min-h-9 rounded-lg border border-cyan-200 px-3 py-2 text-xs font-semibold text-cyan-800 hover:bg-cyan-50">{{ __('Otvori') }}</button></td></tr>@empty<tr><td colspan="5" class="px-3 py-8 text-center text-sm text-slate-500">{{ __('Još nema obrade slika za odabrane filtre.') }}</td></tr>@endforelse</tbody></table></div>
        <div class="mt-4">{{ $runs->links() }}</div>
    </section>
</div>
